### ISSUE TITLE
Problem during the autoscale:create_ami

### ISSUE THREAD

**Issue by vnikitov** [KentaaNL/capistrano-autoscale#1]
I had a problem during the AMI creation.
I follow the README also use Launch templates for the Autoscaling.
Deploy itself was successful ami creation was started, but the task failed

```
autoscaling: Auto Scaling Group: asg-test
Autoscaling: Selecting instance to create AMI from...
Autoscaling: Instance i-0590b404cd9229815 entering standby state...
Autoscaling: Creating AMI from i-0590b404cd9229815 
(Backtrace restricted to imported tasks)
cap aborted!
ArgumentError: missing required option :id

Tasks: TOP => autoscale:create_ami
(See full trace by running task with --trace)
The deploy has failed with an error: missing required option :id
```

Do you have any idea what I'm missing?

**Comment by ppostma** [comment]
Not sure, but maybe something do to with permissions to create AMIs?

I don't recommend using this gem at the moment. We experienced too many issues and are currently working on a different solution that use instance refresh on the Auto Scaling Groups. We hope to publish this soon on github.
