### ISSUE TITLE
Non-Rails use

### ISSUE THREAD

**Issue by augustosamame** [KentaaNL/capistrano-autoscale#2]
Is there any limitation of whether this gem HAS to be used with Rails?
I'm looking to use it for Django deployments as I haven't been able to find an equivalent, simple solution for Python.
As long as Ruby is installed, this should work right?

**Comment by ppostma** [comment]
This gem makes no assumption of Rails so in theory it might work.

However, I don't recommend using this gem at the moment. We experienced too many issues and are currently working on a different solution that use instance refresh on the Auto Scaling Groups. We hope to publish this soon on github.
